= Galimatias Library

== build.gradle

```groovy
repositories {
  xp.enonicRepo()
}

dependencies {
  include 'com.enonic.lib:lib-galimatias:1.0.0-SNAPSHOT'
}
```

== Javascript

```javascript
var libGalimatias = require('/lib/galimatias');

// Functional
libGalimatias.parse('https://www.example.com'); // returns string
libGalimatias.normalize('https://www.example.com'); // returns string
libGalimatias.resolve('https://www.example.com', '/path'); // returns string

// Object oriented
var URL = require('/lib/galimatias').URL;

// Static
URL.parse('https://www.example.com'); // returns string
URL.normalize('https://www.example.com'); // returns string
URL.resolve('https://www.example.com', '/path'); // returns string

// Instance
var url = new URL('https://www.example.com#fragment'); // returns Object
url.toString(); // returns string
url.normalize(); // returns string
url.resolve('/path'); // returns string

url.fromString('ftp://ftp.example.com').normalize(); // fromString is chainable

url.getFragment(); // returns string
url.setFragment('').getFragment(); // setFragment is chainable

url.getHost(); // returns string
url.setHost('www.iana.org').getHost(); // setHost is chainable

url.getScheme(); // returns string
url.setScheme('http').getScheme(); // setScheme is chainable
```

== Compatibility

[width="50%",options="header"]
|===
| Version | Min XP version
|===
|1.0.0-B3-SNAPSHOT |7.5.0
|1.0.0-B2 |7.4.1
|1.0.0-B1 |7.0.x
|===

== Changelog

=== 1.0.0-B3-SNAPSHOT

* Require Enonic 7.5.0
* Buildsystem upgrades
  * Node 14.16.0
  * Removed unused node modules (styling related)
  * Webpack 5.24.2
  * All node modules up to date

=== 1.0.0-B2

* Require Enonic 7.4.1
* Buildsystem upgrades
  * Node 14.15.4
  * Upgrade node modules

=== 1.0.0-SNAPSHOT

* Added URL class
* Added static parse
* Exported functional parse

* Added static normalize
* Exported functional normalize
* Added normalize method

* Added static resolve
* Exported functional resolve
* Added resolve method

* Added getFragment method
* Added setFragment method

* Added getHost method
* Added setHost method

* Added fromString method

* Added getScheme method
* Added setScheme method

== Build

```bash
enonic project deploy
```

== Publishing

```bash
enonic project gradle -- clean build publishToMavenLocal publish --refresh-dependencies
```
